name: All Required Checks

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed, edited]

concurrency:
  group: approval-check-${{ github.event.pull_request.number }}
  cancel-in-progress: false

jobs:
  check-approvals:
    name: SME and QA Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests

      - name: Run SME and Quality Approval Check
        env:
          GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SME_TEAM: 'sme'
          QUALITY_TEAM: 'quality'
        run: | 
            python scripts/check_approval_count.py
            # python scripts/check_approval_count.py || true
            # echo "Simulating success for testing"
            # exit 0  
  check:
    name: All Required Checks
    if: always()
    needs:
      - check-approvals
    runs-on: ubuntu-latest

    steps:
      - name: Fail if any needed job did not succeed
        if: needs.check-approvals.result != 'success'
        run: |
          echo "One or more required jobs failed."
          exit 1

      - name: All required checks passed
        if: needs.check-approvals.result == 'success'
        run: echo "All required jobs succeeded."
