name: SME and Quality Approval Check

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review, review_requested, edited]
  pull_request_review:
    types: [submitted, dismissed, edited]
    
concurrency:
  group: approval-check-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-approvals:
    name: SME and QA Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests

      - name: Run SME and Quality Approval Check
        env:
          GITHUB_TOKEN: ${{ secrets.SAML_GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          SME_TEAM: 'sme'
          QUALITY_TEAM: 'quality'
        run: python scripts/check_approval_count.py
  check:
    name: All Required Checks
    if: always()
    needs:
    - check-approvals

    runs-on: ubuntu-latest

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        jobs: ${{ toJSON(needs) }}
